### ISSUE TITLE
Implement an unlock code for flash writing

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-firmware#30]
In order to prevent inadvertent writes to non-volatile flash storage in the program memory area, and unlock sequence such as 0xAA55AA or some such string must be prepended.

**Comment by vasutomar** [comment]
Hi, 
I would like to take up this issue, can you please help me get started? 
Which string do I need to change?

**Comment by CloudyPadmal** [comment]
Fixed in #33
