### ISSUE TITLE
bootloader and upgrade feature

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-firmware#62]
# PSLab bootloader

## prerequisites

Microchip already offers source code for a bootloader. See their release notes: https://ww1.microchip.com/downloads/en/DeviceDoc/release_notes_bootloader_v1_18_4.pdf

## regions/sections in flash

This is only an *example*. The exact sizes depend on the sizes of bootloader and
the application.

Questions:

- What is the size of the current application? How is the memory arranged?
  => determines the space left for the bootloader
- What size can we expect from the bootloader? It should be small and leave as
  much space to the application as possible.

`0x000000...0x01ffff     0x020000...0x04ffff    `

`[--- bootloader ---][------ application ------]`

## functionality

- loader: load and run application from specific section in flash
- recovery: drop to loading application from UART in case of boot failure
- upgrade: in application, offer a command to reflash from UART

Reflashing through PICKit is always possible, regardless.

## possible ideas

- trigger recovery through a hardware button / switch => done in application
- hardware switch always triggers recovery on boot (press + hold button when plugging in)

**Comment by CloudyPadmal** [comment]
Added along with other changes in #65
