### ISSUE TITLE
Implement UART read/write operations

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-firmware#66]

**Comment by bessman** [comment]
Is this not already provided by mcc_generated_files/uart*?

**Comment by CloudyPadmal** [comment]
Registry calls are autogenerated. I was going for an approach where we implement UART ops in the state machine.

**Comment by CloudyPadmal** [comment]
`Write_Int` is implemented in #79

**Comment by CloudyPadmal** [comment]
Implemented in #75
